import numpy as np

SIGNAL_PERIOD = 7
SAMPLING_RATE_FACTOR = 4
NB_PERIODS = 12
FREQUENCY = 1 / SIGNAL_PERIOD
SAMPLING_RATE = SAMPLING_RATE_FACTOR * FREQUENCY
NOISE_STD = 0.0
OFFSET = 0
AMPLITUDE = 2
INITIAL_PHASE = np.pi / 8
INITIAL_PHASE = 0
DUPPLICATION_FACTOR = 6
